---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-aws-eks-github-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-aws-eks-github-actions
  template:
    metadata:
      labels:
        app: react-aws-eks-github-actions
    spec:
      containers:
      - name: react-aws-eks-github-actions
        image: codewithmuh/react-aws-eks-github-actions:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react-aws-eks-github-actions-service
spec:
  selector:
    app: react-aws-eks-github-actions
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer