name: Trivy Image Scan Workflow

on:
    workflow_run:
      workflows: 
        - Code Build Workflow
      types:
        - completed
  
jobs:
    build:
      name: Docker Image Scan
      runs-on: self-hosted
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Pull the Docker image From DockerHub
          run: docker pull codewithmuh/react-aws-eks-github-actions:latest

  
        - name: Trivy image scan
          run: trivy image codewithmuh/react-aws-eks-github-actions:latest
  